"""Pydantic models for podcast scripts, episodes, and audio."""

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field


class DialogueType(StrEnum):
    """Type of dialogue segment."""

    OBSERVATION = "observation"
    FACT = "fact"
    STORY = "story"
    QUESTION = "question"
    RESPONSE = "response"
    TRANSITION = "transition"
    INTRO = "intro"
    OUTRO = "outro"


# --- Script Models ---


class ScriptSegment(BaseModel):
    """A single dialogue segment in the podcast script."""

    segment_id: str
    speaker: str
    dialogue: str
    finding_ids: list[str] = Field(default_factory=list)
    dialogue_type: DialogueType = DialogueType.OBSERVATION
    duration_estimate_seconds: float | None = None


class Chapter(BaseModel):
    """A chapter grouping segments by topic."""

    chapter_id: str
    title: str
    start_segment_id: str
    end_segment_id: str
    topic: str | None = None


class PodcastScript(BaseModel):
    """Complete podcast script generated by the Podcast Editor."""

    title: str
    destination_name: str
    episode_minutes_target: int
    personas: list[str]
    chapters: list[Chapter] = Field(default_factory=list)
    segments: list[ScriptSegment] = Field(default_factory=list)
    total_estimated_duration_seconds: float | None = None


# --- Audio Models ---


class AudioSegment(BaseModel):
    """A generated audio segment."""

    segment_id: str
    speaker: str
    audio_data: bytes | None = None
    duration_seconds: float | None = None
    voice_id: str | None = None


class GeneratedEpisode(BaseModel):
    """Final generated episode with all assets."""

    title: str
    destination_name: str
    duration_seconds: int | None = None
    audio_object_key: str | None = None
    transcript_object_key: str | None = None
    metadata_object_key: str | None = None
    chapters: list[dict] = Field(default_factory=list)
    citations: list[dict] = Field(default_factory=list)


# --- Episode Record ---


class PodcastEpisodeRecord(BaseModel):
    """Podcast episode as stored in Supabase."""

    id: UUID
    research_job_id: UUID
    user_id: UUID | None = None
    trip_id: UUID
    stop_id: UUID
    title: str
    destination_name: str
    duration_seconds: int | None = None
    personas: list[str]
    chapters: list[dict] | None = None
    citations: list[dict] | None = None
    audio_object_key: str | None = None
    transcript_object_key: str | None = None
    metadata_object_key: str | None = None
    generated_at: datetime


# --- Citation ---


class Citation(BaseModel):
    """A citation linking a podcast segment to its source."""

    segment_id: str
    finding_id: str
    source_url: str
    source_title: str | None = None
    claim: str
